---
apiVersion: v1
kind: Namespace
metadata:
  name: fortune-ns
  # used for finding the resource
  labels:
    app: fortune
    version: v1
---
# A deployment is used to manage a group of similar pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: fortune-ns
  labels:
    app: fortune
spec:
  replicas: 2
  selector:
    matchLabels:
      # should match the metadata label of template (AKA pod)
      app: fortune-pod
  template:
    # this is basically "fortune-pod.yaml" AKA telling that this is the pod to create
    metadata:
      name: fortune-pod
      labels:
        app: fortune-pod
    spec:
      containers:
        - name: fortune-container
          image: dockerkoh/fortune:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: for-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  namespace: fortune-ns
  labels:
    app: fortune
spec:
  #type: ClusterIP
  type: LoadBalancer
  selector:
    # route to this group of pods (via labels)
    app: fortune-pod
  ports:
    - name: for-svc-port
      # refers to the port exposed by service
      #port: 8080
      port : 80
      # refers to the port exposed by the port
      targetPort: for-port
