---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  labels:
    app: fortune
    label: v1
  # namespace: fortune-ns (in general, we do not specify namespace in yaml file)
spec:
  containers:
    - name: fortune-container
      image: dockerkoh/fortune:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
