---
apiVersion: v1
kind: Secret
metadata:
  name: nw-secret
  #namespace: nw
  labels:
    app: northwind
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw-deploy
  # namespace: nw (not included)
  labels:
    app: northwind
spec:
  # Because DB is stateful (doesn't make sense to have more than 1 DB)
  replicas: 1
  selector:
    matchLabels:
      app: northwind
  template:
    # this is basically "nw-pod.yaml" AKA telling that this is the pod to create
    metadata:
      name: nwdb-pod
      labels:
        app: northwind
    spec:
      volumes:
        - name: nwdb-vol
          persistentVolumeClaim:
            claimName: nwdb-pvc
        - name: share-dir
          emptyDir: {} # created for each pod and is unique for each pod
      initContainers:
        # specialized containers that run before app containers in a Pod (must terminate before app containers can run)
        # runs sequentially
        - name: busybox
          image: busybox # popular image: just a shell for running stuff
          command:
            - /bin/sh
            - -c
            - "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"
          volumeMounts:
            - name: nwdb-vol
              mountPath: /scrub
            - name: share-dir
              mountPath: /tmp/share
      containers:
        - name: nwdb-container
          image: dockerkoh/nwdb:v3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nw-secret # name of secret
          ports:
            - name: nwdb-port
              containerPort: 3306
          volumeMounts:
            - name: nwdb-vol
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  #namespace: nw
  labels:
    app: northwind
spec:
  # ClusterIP since this is database and should be within the network (not exposed)
  type: ClusterIP
  selector:
    app: northwind
  ports:
    - name: nwdb-svc-port
      port: 3306
      targetPort: nwdb-port